In [1]:
import os
os.chdir("/Users/jacksonwalters/Documents/GitHub/enefit-kaggle/predict-energy-behavior-of-prosumers/")
!ls

client.csv                            gas_prices.csv
county_id_to_name_map.json            historical_weather.csv
electricity_prices.csv                public_timeseries_testing_util.py
enefit                                train.csv
example_test_files                    weather_station_to_county_mapping.csv
forecast_weather.csv


In [4]:
import tensorflow as tf

In [5]:
import pickle
cnn_model=pickle.load(open('../models/cnn_model.sav', 'rb'))

ModuleNotFoundError: No module named 'keras.src'

In [6]:
import numpy as np
import pandas as pd
from load_data import merged_df

In [5]:
df = merged_df()

loading train data...
loading gas_prices...
loading electricity_prices...
loading forecast_weather...
merging train and gas_prices...
merging electricity_prices...
merging forecast_weather...


In [7]:
df

county  is_business  product_type   target  is_consumption  \
2928           0            0             1    1.687               0   
2929           0            0             1    1.687               0   
2930           0            0             1    1.687               0   
2931           0            0             1    1.687               0   
2932           0            0             1    1.687               0   
...          ...          ...           ...      ...             ...   
11318433      15            1             3  170.135               1   
11318434      15            1             3  170.135               1   
11318435      15            1             3  170.135               1   
11318436      15            1             3  170.135               1   
11318437      15            1             3  170.135               1   

          prediction_datetime  data_block_id   row_id  prediction_unit_id  \
2928             1.630555e+09              1     2928                   0   
2929             1.630555e+09              1     2928                   0   
2930             1.630555e+09              1     2928                   0   
2931             1.630555e+09              1     2928                   0   
2932             1.630555e+09              1     2928                   0   
...                       ...            ...      ...                 ...   
11318433         1.685419e+09            636  2012241                  60   
11318434         1.685419e+09            636  2012241                  60   
11318435         1.685419e+09            636  2012241                  60   
11318436         1.685419e+09            636  2012241                  60   
11318437         1.685419e+09            636  2012241                  60   

          forecast_date  ...  cloudcover_high  cloudcover_low  cloudcover_mid  \
2928       1.630555e+09  ...         0.000000        0.043335        0.835190   
2929       1.630555e+09  ...         0.000000        0.158173        0.370102   
2930       1.630555e+09  ...         0.000000        0.196793        0.158386   
2931       1.630555e+09  ...         0.000000        0.119019        0.164139   
2932       1.630555e+09  ...         0.000000        0.226669        0.194443   
...                 ...  ...              ...             ...             ...   
11318433   1.685419e+09  ...         0.000000        0.000000        0.881360   
11318434   1.685419e+09  ...         0.000000        0.000000        0.894925   
11318435   1.685419e+09  ...         0.000000        0.000000        0.977231   
11318436   1.685419e+09  ...         0.000000        0.000000        0.999768   
11318437   1.685419e+09  ...         0.738403        0.000000        0.999997   

          cloudcover_total  10_metre_u_wind_component  \
2928              0.837845                   0.971769   
2929              0.393387                   0.535612   
2930              0.238663                   1.305875   
2931              0.186142                   1.239103   
2932              0.290100                   1.273527   
...                    ...                        ...   
11318433          0.881360                   4.665982   
11318434          0.894925                   5.060758   
11318435          0.977231                   5.516080   
11318436          0.999768                   5.150113   
11318437          0.999997                   2.701138   

         10_metre_v_wind_component  direct_solar_radiation  \
2928                    -10.245974                     0.0   
2929                     -5.105104                     0.0   
2930                     -7.770632                     0.0   
2931                     -9.215212                     0.0   
2932                     -9.503542                     0.0   
...                            ...                     ...   
11318433                 -1.810666                     0.0   
11318434                 -2.906857                     0.0   
1131

In [7]:
cnn_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d (Conv1D)             (None, 1, 32)             8096      
                                                                 
 dense (Dense)               (None, 1, 32)             1056      
                                                                 
 dense_1 (Dense)             (None, 1, 1)              33        
                                                                 
Total params: 9,185
Trainable params: 9,185
Non-trainable params: 0
_________________________________________________________________


In [8]:
#create a prediction df with all target values set to zero
predict_df = df[:1000].copy()
predict_df['target'] = 0.

In [9]:
#just use a smaller amount of data
df = df[:10_000].copy()

In [10]:
#test-train-validation split on the data
column_indices = {name: i for i, name in enumerate(df.columns)}

n = len(df)
train_df = df[0:int(n*0.7)]
val_df = df[int(n*0.7):int(n*0.9)]
test_df = df[int(n*0.9):]

num_features = df.shape[1]

#normalize the training data
train_mean = train_df.mean()
train_std = train_df.std()

if train_std['target'] == 0.:
    print("AHHHHHH!!!!!")

train_df = (train_df - train_mean) / train_std
val_df = (val_df - train_mean) / train_std
test_df = (test_df - train_mean) / train_std

#Handle the indexes and offsets as shown in the diagrams above.
#Split windows of features into (features, labels) pairs.
#Plot the content of the resulting windows.
#Efficiently generate batches of these windows from the training, evaluation, and test data, using tf.data.Datasets.
class WindowGenerator():
  def __init__(self, input_width, label_width, shift,
               train_df=train_df, val_df=val_df, test_df=test_df,
               label_columns=None):
    # Store the raw data.
    self.train_df = train_df
    self.val_df = val_df
    self.test_df = test_df

    # Work out the label column indices.
    self.label_columns = label_columns
    if label_columns is not None:
      self.label_columns_indices = {name: i for i, name in enumerate(label_columns)}
    self.column_indices = {name: i for i, name in enumerate(train_df.columns)}

    # Work out the window parameters.
    self.input_width = input_width
    self.label_width = label_width
    self.shift = shift

    self.total_window_size = input_width + shift

    self.input_slice = slice(0, input_width)
    self.input_indices = np.arange(self.total_window_size)[self.input_slice]

    self.label_start = self.total_window_size - self.label_width
    self.labels_slice = slice(self.label_start, None)
    self.label_indices = np.arange(self.total_window_size)[self.labels_slice]

  def __repr__(self):
    return '\n'.join([
        f'Total window size: {self.total_window_size}',
        f'Input indices: {self.input_indices}',
        f'Label indices: {self.label_indices}',
        f'Label column name(s): {self.label_columns}'])

def split_window(self, features):
  inputs = features[:, self.input_slice, :]
  labels = features[:, self.labels_slice, :]
  if self.label_columns is not None:
    labels = tf.stack([labels[:, :, self.column_indices[name]] for name in self.label_columns],axis=-1)

  # Slicing doesn't preserve static shape information, so set the shapes
  # manually. This way the `tf.data.Datasets` are easier to inspect.
  inputs.set_shape([None, self.input_width, None])
  labels.set_shape([None, self.label_width, None])

  return inputs, labels

WindowGenerator.split_window = split_window

def make_dataset(self, data):
  data = np.array(data, dtype=np.float32)
  ds = tf.keras.utils.timeseries_dataset_from_array(
      data=data,
      targets=None,
      sequence_length=self.total_window_size,
      sequence_stride=1,
      shuffle=True,
      batch_size=32,)

  ds = ds.map(self.split_window)

  return ds

WindowGenerator.make_dataset = make_dataset

@property
def train(self):
  return self.make_dataset(self.train_df)

@property
def val(self):
  return self.make_dataset(self.val_df)

@property
def test(self):
  return self.make_dataset(self.test_df)

@property
def example(self):
  """Get and cache an example batch of `inputs, labels` for plotting."""
  result = getattr(self, '_example', None)
  if result is None:
    # No example batch was found, so get one from the `.train` dataset
    result = next(iter(self.train))
    # And cache it for next time
    self._example = result
  return result

WindowGenerator.train = train
WindowGenerator.val = val
WindowGenerator.test = test
WindowGenerator.example = example

/var/folders/4d/rp7dhwss6znf18sks0v304d80000gn/T/ipykernel_1887/3339130459.py:12: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  train_mean = train_df.mean()
/var/folders/4d/rp7dhwss6znf18sks0v304d80000gn/T/ipykernel_1887/3339130459.py:13: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  train_std = train_df.std()


In [11]:
#multi-step dense network
CONV_WIDTH = 9
conv_window = WindowGenerator(
    input_width=CONV_WIDTH,
    label_width=1,
    shift=1,
    label_columns=['target'])

In [12]:

conv_window

Total window size: 10
Input indices: [0 1 2 3 4 5 6 7 8]
Label indices: [9]
Label column name(s): ['target']

In [13]:
print('Input shape:', conv_window.example[0].shape)
print('Output shape:', cnn_model(conv_window.example[0]).shape)

Input shape: (32, 9, 29)


2023-12-15 16:11:46.245251: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 9, 28), found shape=(32, 9, 29)

In [148]:
conv_window.example[1]

<tf.Tensor: shape=(32, 1, 1), dtype=float32, numpy=
array([[[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]]], dtype=float32)>

In [147]:
cnn_model.predict(conv_window.example[0])

array([[[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]],

       [[0.2711371]]], dtype=float32)

In [119]:
#note that the train, test, validation data all have a second "label"representing the target value
cnn_model.predict(conv_window.example[0]) - conv_window.example[1]

<tf.Tensor: shape=(32, 1, 1), dtype=float32, numpy=
array([[[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]]], dtype=float32)>